server:
  hostname: 'API_HOSTNAME'
  port: 'PORT'
  adminPort: 'ADMIN_PORT'

authentication:
  username: 'USER'
  password: 'PASSWD'

dataSources:
  http:
    baseUri: 'DOCUSIGN_API_BASEURI'
    username: 'DOCUSIGN_USERNAME'
    password: 'DOCUSIGN_PASSWORD'
    integratorKey: 'DOCUSIGN_INTEGRATOR_KEY'
