server:
  hostname: 'API_HOSTNAME'
  port: 'PORT'
  adminPort: 'ADMIN_PORT'

authentication:
  username: 'USER'
  password: 'PASSWD'

dataSources:
  http:
    baseUri: 'DOCUSIGN_API_BASEURI'
    headers:
      X-DocuSign-Authentication:
        Username: 'DOCUSIGN_USERNAME'
        Password: 'DOCUSIGN_PASSWORD'
        IntegratorKey: 'DOCUSIGN_INTEGRATOR_KEY'
