server:
  protocol: https
  hostname: ${API_HOSTNAME}
  port: ${PORT}
  adminPort: ${ADMIN_PORT}
  basePathPrefix: /api
  keyPath: /path/to/key.pem
  certPath: /path/to/server.crt
  secureProtocol: TLSv1_2_method

authentication:
  username: ${USER}
  password: ${PASSWD}

dataSources:
  dataSources: [http']
  http:
    baseUri: ${DOCUSIGN_API_BASEURI}
    headers:
      Accept: application/json
      Content-Type: application/json
      X-DocuSign-Authentication:
        Username: ${DOCUSIGN_USERNAME}
        Password: ${DOCUSIGN_PASSWORD}
        IntegratorKey: ${DOCUSIGN_INTEGRATOR_KEY}
